### PR TITLE
fix(typescript): capture missed CALLS edges from HOF callbacks and JSX

### LINKED ISSUE #1166: CALLS edge collector misses ~75% of functions; concentrated in HOF/callback patterns
### Area

gitnexus (CLI / core / indexing / MCP server)

## TL;DR

`Function` nodes are indexed correctly (100%), but the **CALLS edge collector silently drops most call expressions** when the call sits inside a callback that's passed as an argument to another function (HOF pattern). In one typical TS+React codebase:

- **75%** of all functions have zero outgoing CALLS edges
- **56%** of all functions are fully orphaned (no CALLS edges either direction)
- Some file classes (Zustand stores, React providers) hit **0%** capture rate

Downstream effect: `context().incoming/outgoing` returns `{}` and `impact(direction: "upstream")` returns `risk: LOW, impactedCount: 0` for symbols that have many real callers/callees, silently mis-reporting blast radius.

## Quantified scope (one repo)

```cypher
MATCH (f:Function) RETURN count(f) AS totalFunctions
-- 1813
```

```cypher
MATCH (f:Function)
WHERE NOT EXISTS { MATCH (f)-[:CodeRelation {type: 'CALLS'}]->() }
RETURN count(f) AS orphansNoOutgoingCalls
-- 1362  (75%)
```

```cypher
MATCH (f:Function)
WHERE NOT EXISTS { MATCH ()-[:CodeRelation {type: 'CALLS'}]->(f) }
RETURN count(f) AS orphansNoIncomingCalls
-- 1323  (73%)
```

```cypher
MATCH (f:Function)
WHERE NOT EXISTS { MATCH (f)-[:CodeRelation {type: 'CALLS'}]->() }
  AND NOT EXISTS { MATCH ()-[:CodeRelation {type: 'CALLS'}]->(f) }
RETURN count(f) AS fullyOrphanedFunctions
-- 1013  (56%)
```

```cypher
MATCH (f:Function)
WHERE NOT EXISTS { MATCH (f)-[:CodeRelation]->() }
  AND NOT EXISTS { MATCH ()-[:CodeRelation]->(f) }
RETURN count(f) AS noEdgesAtAll
-- 0
```

So every function gets structural edges (CONTAINS, DEFINES, etc.) — only the **CALLS** edge collector is failing.

## Pattern correlation

Per-file capture rate (sample):

| File | Functions | With outgoing CALLS | Capture rate | Pattern |
|---|---:|---:|---:|---|
| `clients/*/src/stores/system-settings-store.ts` | 21 | 0 | **0%** | Zustand `create()(devtools(persist(...)))` |
| `clients/*/src/stores/personalization-store.ts` | 18 | 0 | **0%** | Zustand store |
| `clients/*/src/stores/update-store.ts` | 17 | 0 | **0%** | Zustand store |
| `clients/*/src/stores/feedback-store.ts` | 13 | 0 | **0%** | Zustand store |
| `clients/*/src/stores/widget-token-store.ts` | 13 | 0 | **0%** | Zustand store |
| `clients/*/src/stores/bucket-store.ts` | 12 | 0 | **0%** | Zustand store |
| `clients/*/src/stores/s3-chat-store.ts` | 10 | 0 | **0%** | Zustand store |
| `clients/desktop/src/api/gateway-provider.tsx` | 13 | 0 | **0%** | React Context provider |
| `libs/tools/src/utils/index.ts` | 15 | 0 | **0%** | Re-export aggregator |
| `clients/*/src/hooks/use-gateway-queries.ts` | 49 | 2 | **4%** | TanStack `useQuery`/`useMutation` |
| `clients/*/src/components/chat-log.tsx` | 23 | 4 | **17%** | Large React component |
| `clients/*/src/utils/file-upload.ts` | 12 | 2 | **17%** | `new Promise(...)`, `Promise.all(.map(...))` |
| `clients/desktop/src/views/main-view.tsx` | 16 | 4 | **25%** | React view |
| `servers/service-gateway/src/services/stripe-service.ts` | 26 | 11 | **42%** | Service class with adapters |
| `servers/service-gateway/src/auth/auth-utils.ts` | 28 | 16 | **57%** | Plain async helpers |
| `clients/web/src/utils/token-estimation.ts` | ~10 | ~10 | **~100%** | Plain sync helpers |
| `clients/web/src/utils/network-retry.ts` | ~5 | ~5 | **~100%** | Plain helpers |
| `clients/web/src/utils/time-format.ts` | ~5 | ~5 | **~100%** | Plain helpers |

Diagnostic Cypher:

```cypher
MATCH (f:Function)
WITH f, EXISTS { MATCH (f)-[:CodeRelation {type: 'CALLS'}]->() } AS hasCalls
WITH f.filePath AS file, hasCalls
RETURN file,
       count(*) AS total,
       sum(CASE WHEN hasCalls THEN 1 ELSE 0 END) AS withCalls,
       sum(CASE WHEN hasCalls THEN 0 ELSE 1 END) AS orphans
ORDER BY orphans DESC LIMIT 25
```

## Hypothesis

The AST walker **stops at the first call-expression boundary** when collecting CALLS edges, so calls *inside callbacks passed as arguments to other function calls* aren't traversed. This explains the gradient cleanly:

```ts
// ✅ captured — direct call in body
export const foo = () => {
  bar();
};

// ✅ captured — direct call in arrow-fn body
export const foo = async () => {
  await bar();
  return baz();
};

// ❌ NOT captured — call inside callback passed to HOF
export const useStore = create<State>()(
  devtools(persist((set, get) => ({
    addItem: (item) => set(state => doSomething(state, item)), // doSomething not edged
    fetchData: async () => {
      const result = await api.fetch();           // api.fetch not edged
      return result;
    },
  }), { name: 'store' }))
);

// ❌ NOT captured — call inside Promise constructor callback
export const fileToDataUrl = (file: File): Promise<string> =>
  new Promise((resolve, reject) => {
    const reader = new FileReader();        // FileReader not edged
    reader.onload = () => resolve(reader.result as string);
    reader.readAsDataURL(file);             // readAsDataURL not edged
    reader.onerror = () => reject(reader.error);
  });

// ❌ NOT captured — call inside .map callback inside Promise.all
export const processSelectedFiles = async (files: File[]) => {
  const results = await Promise.all(files.map(file => processFile(file))); // processFile not edged
};

// ❌ NOT captured — TanStack Query factory
export const useUserQuery = () =>
  useQuery({
    queryFn: () => api.getUser(),           // api.getUser not edged
    queryKey: ['user'],
  });
```

This gradient — plain helpers ≈100%, services ≈40-60%, HOF-heavy modules ≈0% — matches the prediction exactly.

### Expected behavior

For `file-upload.ts`, expected at least these CALLS edges (from reading the source):

| caller | callee |
|---|---|
| `validateFile` | `sharedValidateFile` (imported) |
| `validateImageFile` | `sharedValidateImageFile` (imported) |
| `validateRequestSize` | `validateAndOptimizeRequestSize` |
| `processFile` | `validateFile` |
| `processFile` | `fileToDataUrl` |
| `processImageFile` | `processFile` |
| `handleFileUpload` | `openFilePicker` |
| `handleFileUpload` | `processSelectedFiles` |
| `handleImageUpload` | `openImageFilePicker` |
| `handleImageUpload` | `processSelectedFiles` |
| `processSelectedFiles` | `validateAndOptimizeRequestSize` |
| `processSelectedFiles` | `processFile` |

That's **12 missing edges**; only 3 captured (~20% capture rate for this file vs ~100% for sibling files).

### Actual behavior

Graph contains the function nodes but the call expressions inside their bodies are not converted to CALLS edges, except for the 3 cross-file calls listed in query 2. As a downstream effect, `context({name: "processFile"}).incoming` returns `{}` and `impact({target: "processFile", direction: "upstream"})` returns `risk: LOW, impactedCount: 0`, which silently misleads agents/users about blast radius.

## Reproduction

Repository: indexed via `gitnexus analyze --embeddings --skills` on a TS/Nx monorepo.

## Concrete repro (single file)

File: `clients/web/src/utils/file-upload.ts` (~556 lines, 12 top-level `export const fn = ...` functions).

```cypher
-- 1. Confirm all 12 functions are indexed as nodes
MATCH (n:Function)
WHERE n.filePath = 'clients/web/src/utils/file-upload.ts'
RETURN n.name, n.startLine
ORDER BY n.startLine

-- Returns: 12 rows ✅
```

```cypher
-- 2. Outgoing CALLS edges from this file
MATCH (a:Function)-[r:CodeRelation {type: 'CALLS'}]->(b)
WHERE a.filePath = 'clients/web/src/utils/file-upload.ts'
RETURN a.name AS caller, b.name AS callee, b.filePath
```

Returns only **3 rows**, all to *cross-file callees* called directly in a function body:

| caller | callee | calleeFile |
|---|---|---|
| `processFile` | `estimateAttachmentTokens` | `clients/web/src/utils/token-estimation.ts` |
| `validateAndOptimizeRequestSize` | `calculateAttachmentsSize` | `libs/tools/src/utils/index.ts` |
| `validateAndOptimizeRequestSize` | `getBase64SizeKB` | `libs/tools/src/utils/index.ts` |

Expected (12+ edges from reading the source):

| caller | callee | What's between them |
|---|---|---|
| `validateFile` | `sharedValidateFile` | direct call |
| `validateImageFile` | `sharedValidateImageFile` | direct call |
| `validateRequestSize` | `validateAndOptimizeRequestSize` | direct call |
| `processFile` | `validateFile` | direct call |
| `processFile` | `fileToDataUrl` | `await` direct call |
| `processImageFile` | `processFile` | direct return |
| `handleFileUpload` | `openFilePicker` | `await` direct call |
| `handleFileUpload` | `processSelectedFiles` | direct return |
| `handleImageUpload` | `openImageFilePicker` | `await` direct call |
| `handleImageUpload` | `processSelectedFiles` | direct return |
| `processSelectedFiles` | `validateAndOptimizeRequestSize` | direct call |
| `processSelectedFiles` | `processFile` | inside `Promise.all(files.map(file => processFile(file)))` |

Of the 12 expected edges, only the 1 in the cross-file table above (`processFile → estimateAttachmentTokens`) was captured from this file. **Even direct synchronous calls in plain function bodies were missed for this file**, suggesting the issue isn't *purely* HOF-callback related — there may be a secondary parser-state bug where one bad construct in a file (e.g. a `new Promise((resolve, reject) => ...)` with a complex body) corrupts edge collection for sibling functions in the same file.

```cypher
-- 3. Verify 5 specific functions have NO outgoing edges of any type
MATCH (a)-[r:CodeRelation]->(b)
WHERE a.filePath = 'clients/web/src/utils/file-upload.ts'
  AND a.name IN ['processSelectedFiles','handleFileUpload','openFilePicker','processImageFile','validateFile']
RETURN labels(a), a.name, r.type, b.name LIMIT 50

-- Returns: 0 rows
```

```cypher
-- 4. Control: same-file CALLS edges are captured fine in sibling utility files
MATCH (a:Function)-[r:CodeRelation {type: 'CALLS'}]->(b:Function)
WHERE a.filePath = b.filePath
  AND a.filePath CONTAINS 'clients/web/src/utils'
RETURN a.filePath, a.name, b.name LIMIT 20

-- Returns: 11+ rows from token-estimation.ts, 4+ from time-format.ts,
--          4+ from network-retry.ts, 1 from prompt-utils.ts
--          ZERO from file-upload.ts
```

## Suggested fix direction (informed guess)

If the parser uses a single AST visitor with mutable state for collecting CALLS edges, possible problems:

1. **Visitor doesn't recurse into argument expressions** of call expressions — only descends into function bodies. Would fix the "callback inside HOF" case (Zustand, TanStack, etc.).
2. **Visitor short-circuits on first parse error / unrecognized construct** in a file, skipping all subsequent functions. Would explain why simple direct calls in `file-upload.ts` were missed alongside the HOF stuff.
3. **Symbol resolution is by-name within local scope only** — when an arrow function inside a callback references an outer-scope name, the resolver can't bind it. Likely contributes to (1).

Verbose/debug logs on the AST walker for one of the 0%-capture files (e.g. any Zustand store) would probably surface the root cause quickly.

## Severity

**Medium-high.** Indexer doesn't crash and `query` (semantic + BM25) still works because it ranks via process-membership and embeddings rather than raw CALLS edges. But:

- `context(symbol).incoming/outgoing` is unreliable for ~75% of functions
- `impact(target, direction: "upstream")` reports `risk: LOW, impactedCount: 0` for symbols with many real callers — actively misleading agents that trust it for blast-radius decisions
- Affected file classes (Zustand stores, TanStack hooks, React providers) are extremely common in modern TS projects, so any non-trivial frontend codebase will likely see similar 0-50% capture rates

## Workaround

Lead with `query` (semantic search + process ranking is robust to missing edges) and fall back to text search (`grep`/`rg`) when looking for callers of a symbol. Don't trust `impact(direction: "upstream")` numbers without cross-checking.

### Environment

- `gitnexus` version: **1.6.3**
- Node: 22.22.0
- OS: macOS (darwin 25.4.0)
- Project: TypeScript monorepo (Nx 22, pnpm 9.15)
- Code style: `export const fn = async (...) => { ... }` (named arrow-function exports)

### Logs / screenshots

_No response_

### PR DESCRIPTION
**Pull request by ReidenXerx**
Fixes #1166.

## Summary

This is the **umbrella PR for issue #1166** — `Function` nodes had zero outgoing `CALLS` edges for ~73% of all TypeScript functions in real React + TanStack + Zustand codebases. The umbrella consolidates two complementary fix-sets that hit the same root cause from different angles:

- **Registry-primary scope-resolution (originally PR #1175 / `@ReidenXerx`)** — closes two architectural gaps in the migrated TS path: HOF/arrow-callback caller-attribution (`query.ts` arrow anchor + `finalize-algorithm.ts` callable preference + `ids.ts` Variable exclusion) and JSX-as-call edge emission (TSX-only `query.ts` suffix + `captures.ts` phantom-ACCESSES suppression).
- **Legacy Call-Resolution DAG + named object-property arrows (originally PR #1179 / `@abhigyanpatwari`, merged in via `bb6aa0c8`)** — fixes parallel attribution gaps in the legacy path that the registry-primary fix can't reach: `genericFuncName` returning phantom Function IDs for unparenthesized arrows like `file => fn(file)` (Bug A), and `tsExtractFunctionName` failing to name arrows under `pair` parents like `addItem: (item) => set(...)` (Bug B). Adds 4 `pair`-with-arrow declaration patterns to the registry-primary `query.ts` so the two paths agree on which nodes are functions.

Per `AGENTS.md`, TypeScript is in `MIGRATED_LANGUAGES` so the registry-primary path is authoritative for production behavior — but the CI parity gate runs both paths per migrated language on every PR, so the legacy-path fixes were a hard requirement to unify the two paths' definition sets and keep the gate green.

On the bug reporter's repo (`Sourcerer-fe`, scoped to `src/` production code only, with `src/types/` declarations excluded — the repo has zero tests / `.d.ts` / stories / build artifacts in the index): **`Function`→`Function` `CALLS` edges grow from 818 to 1,378 (+560, +68.5%)**. Function-node count grows from 1,185 to 1,560 because the legacy-path fix promotes 375 previously-anonymous object-property arrows (Zustand actions, TanStack `queryFn`, React Context configs) into proper named functions with their own caller scopes — every one of those is a brand-new `gitnexus_impact` target that didn't exist on `main`.

## Motivation / context

Issue #1166 reported quantified observations: `Function` nodes were indexed correctly (100%) but the **CALLS edge collector silently dropped most call expressions** when the call sat inside a callback passed as an argument to another function. In one typical TS+React codebase: 75% of all functions had zero outgoing CALLS, 56% were fully orphaned, and some file classes (Zustand stores, React providers) hit 0% capture. Downstream effect: `gitnexus_context()` returned `{}` for hot symbols, and `gitnexus_impact("Badge", direction: "upstream")` returned `risk: LOW, impactedCount: 0` for components used 15+ times — silently mis-reporting blast radius.

The orphan rate was driven by **four cooperating issues across both call-resolution pipelines**:

### Registry-primary path (TypeScript is in `MIGRATED_LANGUAGES`, so this is authoritative)

1. **HOF / arrow-callback attribution.** `pass2AttachDeclarations` placed the `Function` def for arrow-typed declarations on the wrapping module scope (the `@declaration.function` anchor was the outer `lexical_declaration`, whose start lay before the inner arrow's scope). `resolveCallerGraphId` then walked up past the empty arrow scope into the module and grabbed the first Function-like def in `ownedDefs` — frequently the wrong one. Calls inside `Promise.all(items.map(x => fn(x)))`, `useQuery({ queryFn: () => fetchData() })`, or `create()(devtools(persist((set) => ({ ... }))))` were either lost or attributed to a sibling. As a follow-on, `findExportByName` returned whichever def appeared first in `localDefs` — frequently the `Variable` def TS emits alongside every `const fn = () => {}`, breaking cross-file callee discovery whenever the import resolved to the non-callable. As a third follow-on, the caller walk-up's class-fallback considered any linkable label as a valid caller anchor, including `Variable`, which produced phantom `Function:create → Function:create` self-loops at module scope (Zustand store-creation idiom).

2. **JSX as a CALLS edge.** `<Foo />` is syntactic sugar for `Foo(props)` invoked at runtime by React, but the TS scope query had no `jsx_*` patterns, so React-component invocations were invisible to the call graph. Every `<Component />` in every `.tsx` file produced zero outgoing edges from the enclosing function (and zero incoming edges to the component) — the dominant cause of the .tsx-vs-.ts asymmetry in the orphan rate.

### Legacy Call-Resolution DAG (still runs in parallel for the CI parity gate)

3. **Bug A — phantom Function IDs.** `genericFuncName` scanned `arrow_function` / `function_expression` children for the first identifier and returned it. For unparenthesized arrows like `file => processFile(file)` the first identifier was the parameter `file`, so calls inside got attributed to a synthetic `Function file` and emitted dangling CALLS edges. User queries like `(:Function)-[:CALLS]->()` never saw them.

4. **Bug B — anonymous object-property arrows.** `tsExtractFunctionName` only named arrows whose parent was `variable_declarator`. `addItem: (item) => set(...)` (Zustand actions, TanStack `queryFn`, React Context providers, config objects) lives under a `pair` parent — treated as anonymous. With no named ancestor up to the file, calls inside fell back to the File and were invisible to `context()` / `impact()`.

The four fixes are orthogonal in failure-mode but cooperate in coverage: registry-primary fixes (1) and (2) restore proper attribution for named arrows; legacy fixes (3) and (4) ensure the parallel path agrees on what counts as a named function and which scope to attribute under. **Crucially, fix (4) also adds 4 `pair`-with-arrow patterns to the registry-primary `query.ts`** so the two paths produce the same set of `Function` nodes — the CI parity gate would have failed otherwise.

This PR is the umbrella consolidation of two contributors' work:
- `@ReidenXerx`'s registry-primary scope-resolution fixes (commits `7be595d3`, `851d2ab7`)
- `@abhigyanpatwari`'s legacy-path attribution fixes from PR #1179 (commit `93a0be23`, merged in via `bb6aa0c8`)

References:
- Issue: #1166 — original bug report with quantified scope (75% no-outgoing, 56% fully orphaned).
- Closes: #1179 (this PR supersedes it; the `pair`-with-arrow patterns are merged in here).
- Architecture: `ARCHITECTURE.md` § Scope-Resolution Pipeline; TypeScript is in `MIGRATED_LANGUAGES`, so it goes through the registry-primary path. The legacy DAG runs in parallel for the CI parity gate per migrated language.

## Areas touched

- [x] `gitnexus/` (CLI / core / MCP server)
- [ ] `gitnexus-web/` (Vite / React UI)
- [ ] `.github/` (workflows, actions)
- [ ] `eval/` or other tooling
- [ ] Docs / agent config only (`AGENTS.md`, `CLAUDE.md`, `.cursor/`, `llms.txt`, etc.)

**Files (umbrella):**

Registry-primary path (`@ReidenXerx`):
- `gitnexus/src/core/ingestion/languages/typescript/query.ts` — arrow-anchor inner-node move + TSX_JSX_QUERY_SUFFIX
- `gitnexus/src/core/ingestion/languages/typescript/captures.ts` — JSX cases in `shouldEmitReadMember` + arity-synthesis JSX comment
- `gitnexus/src/core/ingestion/scope-resolution/graph-bridge/ids.ts` — `isCallerAnchorLabel` Variable exclusion
- `gitnexus-shared/src/scope-resolution/finalize-algorithm.ts` — `findExportByName` callable preference

Legacy DAG path + name-resolution alignment (`@abhigyanpatwari`, merged from #1179):
- `gitnexus/src/core/ingestion/languages/typescript.ts` — `tsExtractFunctionName` resolves names from `pair` parents
- `gitnexus/src/core/ingestion/languages/typescript/query.ts` — adds 4 `pair`-with-arrow patterns to mirror the legacy queries (registry-primary half of fix B)
- `gitnexus/src/core/ingestion/tree-sitter-queries.ts` — same `pair`-with-arrow patterns in TYPESCRIPT_QUERIES / JAVASCRIPT_QUERIES (legacy-path half)
- `gitnexus/src/core/ingestion/utils/ast-helpers.ts` — `genericFuncName` returns null for anonymous JS/TS function-likes

Tests + fixtures:
- `gitnexus/test/integration/resolvers/typescript-hof-callbacks.test.ts` (8 assertions, registry-primary path)
- `gitnexus/test/integration/resolvers/typescript-jsx-as-call.test.ts` (7 assertions, registry-primary path)
- `gitnexus/test/unit/call-attribution-issue-1166.test.ts` (18 assertions, legacy DAG path)
- `gitnexus/test/fixtures/lang-resolution/typescript-hof-callbacks/` (6 fixtures)
- `gitnexus/test/fixtures/lang-resolution/typescript-jsx-as-call/` (8 fixtures)

## Scope & constraints

**In scope**

- HOF / arrow-callback caller-attribution for TypeScript (3 cooperating fixes: arrow-anchor in tree-sitter query, `findExportByName` callable preference, `isCallerAnchorLabel` Variable exclusion).
- JSX-as-call CALLS-edge emission for TSX files (TSX-only query suffix + `shouldEmitReadMember` JSX cases to suppress phantom ACCESSES on `<Foo.Bar />`).
- Two new integration test files (`typescript-hof-callbacks.test.ts` 8 assertions, `typescript-jsx-as-call.test.ts` 7 assertions) plus 13 minimal fixtures pinning the exact patterns from the bug report (TanStack `useQuery`/`useMutation`, Zustand `create()(devtools(persist(...)))`, `Promise.all(map)`, `new Promise(executor)`, self-closing JSX, paired JSX, namespaced `<Foo.Bar />`, nested JSX, lowercase HTML negative test, combined HOF+JSX `const F = () => <X />`).

**Explicitly out of scope / not done here** (the residual `.tsx` orphans after this PR — kept off this PR's surface so review stays focused):

- **External-only callers** (~25% of remaining .tsx orphans) — function bodies whose only calls are to `node_modules` symbols (`twMerge`, `dayjs`, `useState`). Working as intended; would require indexing dependencies. Better addressed at the UX layer ("external-only" label, not "orphan").
- **Bare function-reference passing** (~10%) — `queryFn: fetchData` without an arrow wrapper. Not syntactically a call at the use site; deferred for a follow-up that introduces a `WIRES_TO` edge type or an `indirect: true` flag on `CALLS`.
- **Destructured-from-hook-return + prop-callback invocation** (~30%) — `const { fn } = useStore(); fn()` and `function F({ onChange }) { onChange(x) }`. Both require return-type tracking and/or React data-flow analysis. Larger projects; deferred.
- **End-to-end positive resolution of `<Container.Title />` through an object-literal namespace** (`export const Container = { Title }`). The JSX *capture* is verified in tests (member-call interception suppresses the phantom ACCESSES; the receiver doesn't collapse to the wrong target). The full positive-edge to the leaf `Title` requires the existing compound-receiver resolver to chain through object-literal namespaces — pre-existing gap, orthogonal to JSX-as-call.

### Fix 1 — HOF / arrow-callback attribution (3 cooperating changes)

| File | Change |
|---|---|
| `gitnexus/src/core/ingestion/languages/typescript/query.ts` | `@declaration.function` anchor moved from the wrapping `lexical_declaration` to the inner `arrow_function` / `function_expression` so `anchor.range` aligns with `@scope.function` and `pass2AttachDeclarations` lands the def on the arrow's own scope. |
| `gitnexus-shared/src/scope-resolution/finalize-algorithm.ts` | `findExportByName` now prefers callable / class-like defs (`Function`/`Method`/`Constructor`/`Class`/`Interface`/`Enum`/`Struct`/`Record`/`Trait`/`Namespace`/`Module`/`TypeAlias`) over `Variable` when `localDefs` contains both for the same name. (TS emits two defs per `const fn = () => {}` — a Function and a Variable; capture order silently decided which an importer bound to.) The behavior is a tie-break: when only one def with the name exists, the existing first-match path fires unchanged. |
| `gitnexus/src/core/ingestion/scope-resolution/graph-bridge/ids.ts` | New `isCallerAnchorLabel` predicate (a strict subset of `isLinkableLabel`) restricted to `Function` / `Method` / `Constructor` / `Class` / `Interface` / `Struct` / `Enum`. `Variable` / `Property` are no longer valid caller anchors — module-level call expressions inside `const X = expr(args)` declarations correctly fall through to the `File`-node fallback instead of being mis-attributed to a sibling Function via simpleKey (the Zustand `create()(devtools(persist(...)))` regression). |

### Fix 2 — JSX as CALLS edge (2 changes)

| File | Change |
|---|---|
| `gitnexus/src/core/ingestion/languages/typescript/query.ts` | Adds a `TSX_JSX_QUERY_SUFFIX` constant (compiled only against the `tsx` grammar — `jsx_*` node types don't exist in the plain `typescript` grammar, so embedding them in the shared query would throw `Query.InvalidNodeType`). Captures `jsx_self_closing_element` and `jsx_opening_element` as `@reference.call.free` / `@reference.call.member`. Lowercase HTML elements (`<div>`, `<span>`) are filtered with the `(#match? @reference.name "^[A-Z]")` predicate so they don't emit edges to nonexistent targets; member-form (`<Foo.Bar />`) is unfiltered (HTML element names can't contain dots, so any `.`-form is unambiguously a component). The closing tag is intentionally NOT captured — each JSX element should emit exactly one CALLS edge per use site. |
| `gitnexus/src/core/ingestion/languages/typescript/captures.ts` | `shouldEmitReadMember` extended with `jsx_self_closing_element` / `jsx_opening_element` parent cases. Without this, `<Foo.Bar />`'s inner `member_expression` would emit BOTH a `@reference.call.member` (the new path) AND a `@reference.read.member` (the generic catch-all), producing a redundant phantom ACCESSES edge alongside the CALLS edge. Verified by the JSX integration test. |

### Sourcerer-fe end-to-end validation

I built the patched CLI from this branch and re-analyzed the reporter's `Sourcerer-fe` repo at the same commit, three times — clean `main`, registry-primary fixes only (PR #1175 alone), umbrella with legacy-DAG fixes merged in (this PR). Sourcerer-fe is a Next.js + Capacitor mobile app; the indexer respects `.gitignore` and skips `android/`, `ios/`, `node_modules/`, `out/`, `.next/`. Of the 525 indexed files, 508 live in `src/` and the remaining 17 are root configs (`next.config.js`, `tailwind.config.ts`, etc.); the repo has zero test files, zero `.d.ts`, zero stories. Metrics below are scoped to **`src/` only, with `src/types/` declarations excluded** — purely production code patterns.

| Metric | Clean `main` | Registry only (#1175) | **Umbrella (this PR)** | Δ vs main |
|---|---:|---:|---:|---:|
| `Function` nodes (in `src/`) | 1,185 | 1,185 | **1,560** | **+375** |
| **`Function`→`Function` CALLS edges** | **818** | **1,322** | **1,378** | **+560 (+68.5%)** |
| All CALLS edges (incl. File-anchored) | 979 | 1,528 | 1,541 | +562 (+57.4%) |
| .tsx no-outgoing orphans | 521 | 405 | 471 | −50 |
| .ts no-outgoing orphans | 347 | 309 | 586 | +239 (see note) |

**Why the .ts orphan count grows in the umbrella column:** the legacy-path fix (Bug B) promotes 375 previously-anonymous object-property arrows in `.ts` files (Zustand store actions, TanStack hook configs, React Context setup objects) into proper named `Function` nodes. Many of those promoted leaves are tiny one-liners that legitimately have zero outgoing calls (`addItem: (item) => set(...)` only calls `set`, which is itself a parameter), so they appear as orphans-by-numerator while not being a regression. **The right way to read the table:** function count grew by 375 because that many *new* `gitnexus_impact` targets exist that never existed before, and Function→Function edges still grew by 560 — 56 of those edges originate from the newly-promoted leaves and 504 from existing functions that were previously misattributing or invisible.

Concrete bug-report cases that now work:

**Registry-primary path (HOF + JSX):**
- **TanStack hooks** — `src/api-modules/notifications/push-notifications.hooks.ts`: pre-fix 0/16 captures (matches the bug report's "0%" hook number). Post-fix: arrow-form `mutationFn: (data) => registerDevice(data)` correctly emits `useRegisterDevice → registerDevice` and 4 sibling hook-to-API edges.
- **React component invocations** — `src/components/subscription/subscription-management.tsx::getStatusBadge`: previously orphan (its only "call" was `<Badge variant=... />`). Post-fix: `getStatusBadge → Badge` is captured. Across the codebase, `Badge` now has 15 incoming CALLS edges from .tsx files. Top JSX-restored receivers: `cn` (83×), `usePlatform` (37×), `Loader` (35×), `toast` (31×), `useToast` (23×), `Badge` (15×), `TopBarWrapper`/`TopBarPortal` (11× each), Lucide icons like `Share2` (10×) — all 0 incoming on clean `main`.
- **Zustand mis-attribution** — `useStore = create()(devtools(persist((set) => ({ ... }))))` no longer produces phantom `Function:create → Function:create` self-loops. Module-level call expressions correctly fall through to the `File` node when no enclosing function scope owns them (covered by the Zustand-fixture assertions in `typescript-hof-callbacks.test.ts`).

**Legacy DAG path (Bugs A + B):**
- **Phantom `Function file` IDs eliminated** — `processSelectedFiles → processFile` inside `Promise.all(files.map(file => processFile(file)))` previously attributed to a synthetic `Function file` (the parameter name). Now correctly attributes to `processSelectedFiles`.
- **Object-property arrows promoted** — `addItem: (item) => set(...)` and TanStack `queryFn: () => fetchData()` now appear as named `Function` nodes; calls inside their bodies attribute to the action name instead of the file. The reporter's specific Zustand reproducer from #1166 (`useStore = create<State>()(devtools(persist((set, get) => ({ addItem: ..., fetchData: ... }))))`) now resolves all expected edges.

## Testing & verification

Template's standard checklist:

- [x] `cd gitnexus && npm test` — ran the suites covering changed code paths (see custom rows below). Skipped the full `npm test` because the 146 `kotlin.test.ts` failures it would surface are a pre-existing local environment issue (missing optional `tree-sitter-kotlin` native binding, documented in `AGENTS.md` § Gotchas) that reproduces on `main` at `dafda284` without these patches. CI runs the full suite in a clean container where the binding is present.
- [x] `cd gitnexus && npm run test:integration` — covered the relevant subset (changes are confined to TS scope-resolution; integration entry points listed below).
- [x] `cd gitnexus && npx tsc --noEmit` — clean
- [x] `cd gitnexus-web && npx tsc -b --noEmit` — clean (this PR doesn't touch `gitnexus-web/`, but ran per checklist to confirm the `gitnexus-shared` re-exports stay binary-compatible after the `finalize-algorithm.ts` change)
- [ ] `cd gitnexus-web && npm test` — skipped (web not changed)
- [ ] Manual / Playwright E2E — N/A

Specific commands run on the umbrella branch (after merging #1179):

- [x] `cd gitnexus && npx vitest run test/integration/resolvers/typescript-hof-callbacks.test.ts` — **8/8 ✓** (registry-primary HOF assertions)
- [x] `cd gitnexus && npx vitest run test/integration/resolvers/typescript-jsx-as-call.test.ts` — **7/7 ✓** (registry-primary JSX assertions)
- [x] `cd gitnexus && npx vitest run test/unit/call-attribution-issue-1166.test.ts` — **18/18 ✓** (legacy-DAG attribution + Bug A / Bug B assertions, from #1179)
- [x] `cd gitnexus && npx vitest run test/integration/resolvers/typescript.test.ts` — **236/236 ✓** (no regressions in either path)
- [x] `cd gitnexus && npx vitest run test/integration/resolvers/api-deep-flow.test.ts` — **11/11 ✓**
- [x] `cd gitnexus && npx vitest run test/unit/scope-resolution test/unit/scope-extractor test/unit/typescript` — **613/613 ✓**
- [x] **Combined regression run** — all five files in one `vitest run`: **280/280 ✓** (registry-primary integration + legacy-DAG unit + existing TS suite all coexist with both fix sets active)
- [x] `cd gitnexus-shared && npx tsc --noEmit` — clean
- [x] Pre-commit hook (`.husky/pre-commit`) clean during umbrella commits
- [x] End-to-end: re-analyzed `Sourcerer-fe` three times (clean `main`, registry-primary only, umbrella) with patched CLIs; captured the orphan-rate / edge-count numbers in the table above; spot-checked per-file deltas against the specific patterns from #1166 (`file-upload.ts`, `use-gateway-queries.ts`, `grouped-file-uploads-store.tsx`, `push-notifications.hooks.ts`, `subscription-management.tsx`).

## Risk & rollout

**Risk: LOW.**

- Scope is fully contained in the TypeScript scope-resolution path. No behavior change for any other indexed language. The shared library change (`finalize-algorithm.ts::findExportByName`) is a tie-break refinement when both a Function and a Variable definition share a name within the same module — a TypeScript-specific situation; in every other migrated language tested, no callable/variable name collisions of this shape occur in `localDefs`, so the fallback path (first-match) still fires unchanged.
- The new `isCallerAnchorLabel` predicate in `graph-bridge/ids.ts` strictly narrows the existing `isLinkableLabel` predicate (it's a subset). The only legacy behavior it removes is "if the only owned def at module scope is a `Variable`, attribute the call to it as a caller" — a path that produced phantom self-loops in practice (the Zustand regression covered by the test).
- The TSX-only JSX query suffix is appended at TSX-grammar compile time (in `getTsScopeQuery`); plain `.ts` files don't see it. The TSX grammar has been the indexer's `.tsx` path since `MIGRATED_LANGUAGES` flipped — no parser swap.
- Impact analysis (`gitnexus_impact`) on `getTsScopeQuery`, `shouldEmitReadMember`, `emitTsScopeCaptures`, `resolveCallerGraphId`, and `findExportByName` returned `risk: LOW` for all five — direct callers are localized, no execution flows downstream, no cross-module fan-out.
- The legacy-path `genericFuncName` change is a strict narrowing: it returns `null` for anonymous JS/TS function-likes where it previously returned the wrong identifier (the first parameter). Anonymous arrows now correctly fall through to the language hook instead of producing phantom Function IDs.
- The legacy-path `tsExtractFunctionName` change extends naming to `pair` parents (object-property arrows). Computed keys (`[K]: () => ...`) intentionally stay anonymous to avoid resolving runtime expressions. No previously-named function changes its name.
- The 4 new `pair`-with-arrow patterns added to the registry-primary `query.ts` are new pattern matches (not edits to existing patterns) — they only fire on object-property arrows, which previously matched no declaration pattern at all in that path. This is what keeps the CI parity gate green: both pipelines now agree on the set of `Function` nodes.
- 0 regressions across the **280 TypeScript-relevant integration + unit tests** (8 HOF + 7 JSX + 18 issue-1166 + 236 typescript + 11 api-deep-flow) and 613 scope-resolution unit tests on the merged branch.

**Breaking changes: none.** No public API changes (CLI flags, MCP tools, edge types, node labels, schema). The graph emits more edges than before — strictly additive — and eliminates a small number of phantom self-loops. Consumers of the graph (existing `gitnexus_impact` / `gitnexus_query` / `gitnexus_context` callers) will see strictly more truthful results.

**Migrations: none required to ship.** No DB schema change, no node/edge property additions.

**Index refresh: required for users to see the new edges.** Existing indexed repositories will need `npx gitnexus analyze` to surface the additional CALLS edges in their graph (no `--force` needed — the analyzer detects the file/grammar change and re-extracts). Without re-analyzing, existing graphs will continue to render the pre-fix edge set (correct behavior — staleness check writes a marker, see `AGENTS.md` § "If any GitNexus tool warns the index is stale").

**Release notes: lands under 🐛 Bug Fixes** (per `.github/release.yml`, type=`fix`).

**Rollback.** Each of the source-level changes is independently revertible without breaking the others:

Registry-primary path (commits `7be595d3`, `851d2ab7`):

| Revert this | Effect |
|---|---|
| `gitnexus/src/core/ingestion/languages/typescript/query.ts` HOF chunk (arrow-anchor patterns ~lines 151-170) | Restores legacy outer-`lexical_declaration` anchor; HOF-callback caller-attribution returns to pre-fix behavior. JSX and legacy-path fixes still active. |
| `gitnexus-shared/src/scope-resolution/finalize-algorithm.ts` (`findExportByName`) | Returns to first-match behavior across languages. |
| `gitnexus/src/core/ingestion/scope-resolution/graph-bridge/ids.ts` (`isCallerAnchorLabel`) | Reverts to `isLinkableLabel` for caller-walk fallback; phantom self-loop case (Zustand) returns. |
| `gitnexus/src/core/ingestion/languages/typescript/query.ts` `TSX_JSX_QUERY_SUFFIX` (constant + concatenation in `getTsScopeQuery`) | JSX-as-call disabled; HOF and legacy-path fixes still active. |
| `gitnexus/src/core/ingestion/languages/typescript/captures.ts` (jsx cases in `shouldEmitReadMember`) | Phantom ACCESSES edges on `<Foo.Bar />` re-appear; CALLS edges unaffected. |

Legacy DAG path (commit `93a0be23`, originally PR #1179):

| Revert this | Effect |
|---|---|
| `gitnexus/src/core/ingestion/utils/ast-helpers.ts` (`genericFuncName` returning null for anonymous JS/TS) | Phantom Function IDs from unparenthesized arrow parameters re-appear in the legacy path. |
| `gitnexus/src/core/ingestion/languages/typescript.ts` (`tsExtractFunctionName` `pair` parent handling) | Object-property arrows fall back to anonymous in the legacy path; calls inside revert to File attribution. |
| `gitnexus/src/core/ingestion/tree-sitter-queries.ts` `pair`-with-arrow patterns | Legacy queries no longer emit Function nodes for object-property arrows. |
| `gitnexus/src/core/ingestion/languages/typescript/query.ts` 4 `pair`-with-arrow patterns | Registry-primary path no longer produces Function nodes for object-property arrows. **Reverting just this without also reverting the legacy-side patterns will fail the CI parity gate** — the two paths must agree on the Function set. |

A full revert is `git revert <merge-commit>` for the umbrella merge `bb6aa0c8` plus the registry-primary commits. Each commit is independently revertible with `git revert <sha>`. No migrations / data-shape changes. Re-running `npx gitnexus analyze` after a revert restores the pre-fix edge set.

## Checklist

- [x] PR body meets repo minimum length (workflow may label short descriptions)
- [x] If `AGENTS.md` / overlays changed: headers, scope block, and changelog updated per project conventions — **N/A, no overlay files in this PR**
- [x] No secrets, tokens, or machine-specific paths committed — verified by scanning the diff for `/Users/`, `/home/`, `sk-`, `ghp_`, `github_pat_`, `password`, `api_key` (none found)

### CODE REVIEW

**Comment by magyargergo** [comment]
@ReidenXerx can you please look into these findings? 🙏 

Also I so there's a double contribution by @abhigyanpatwari on the other PR you commented on.

**Comment by abhigyanpatwari** [comment]
Hi @magyargergo , I asked @ReidenXerx to rebase of my PR, since this PR is covering more stuff

**Comment by ReidenXerx** [comment]
@magyargergo Thanks for triggering the review — addressed everything in 851d2ab7. Quick summary:

**[medium] `toBeGreaterThan(0)` → `toHaveLength(1)` for combined HOF+JSX**
Caught — a single `<Foo />` is one logical invocation, and the bounds-only assertion would have masked any duplicate-CALLS-edge regression (e.g. if `jsx_self_closing_element` and a generic call pattern ever both matched the same site). Tightened in `typescript-jsx-as-call.test.ts:121`.

**[medium] Zustand "all sources are File" was vacuously true on empty `calls`**
Replaced the `for (c of calls) expect(...)` loop with a structural assertion that's regression-proof either way:
- `fromOther` (anything not File-rooted) must be `[]` — same correctness invariant as before
- `fromFile.length` must be `>0` — proves the `isCallerAnchorLabel` fallback actually fires, not just that we silenced everything

**[low] `findExportByName` comment generality**
Reworked the comment in `gitnexus-shared/src/scope-resolution/finalize-algorithm.ts` to make the language-agnostic nature of the tie-break rule explicit (TypeScript is the first language where this matters in practice, but the rule applies generically — single-def behavior is unchanged for all languages).

**[low] JSX has no arity metadata — undocumented behavior**
Added a comment in `captures.ts` explaining why JSX call anchors intentionally don't synthesize `@reference.arity` (React components aren't overloaded in the current graph model, so name-only dispatch is correct; a JSX-aware synthesizer counting `jsx_attribute` children would be needed if that ever changes).

**`quality / format` CI failure**
Fixed — ran `npx prettier --write` on the 3 flagged files. The pre-commit hook didn't fire on my end because I had a permissions issue on `.git/config` when the husky install would have run (separate sandbox quirk on my workstation, not a project issue).

All 262 affected integration tests still pass locally (8/8 HOF + 7/7 JSX + 236/236 typescript + 11/11 api-deep-flow), `gitnexus` and `gitnexus-shared` typechecks clean. Re-running CI should be green now.

Re: @abhigyanpatwari's note — yes, I'm happy to coordinate on the other PR if there's anything to align on.

**Comment by ReidenXerx** [comment]
@abhigyanpatwari Done — merged your `fix/issue-1166-calls-edges` branch into this one as `bb6aa0c8`. Clean auto-merge, no manual conflict resolution needed.

**Done:**
- ✅ Merged your branch (commit `93a0be23`) into #1175
- ✅ Updated PR title/description to umbrella scope: `Fixes #1166`, `Closes #1179`, both contributors credited, full per-path breakdown of all 4 root causes
- ✅ Re-ran the full TS test surface on the merged branch:
  - 8/8 typescript-hof-callbacks (registry-primary)
  - 7/7 typescript-jsx-as-call (registry-primary)
  - **18/18 call-attribution-issue-1166 (your tests, legacy DAG)**
  - 236/236 typescript.test.ts (no regressions either side)
  - 11/11 api-deep-flow.test.ts
  - 613/613 scope-resolution + scope-extractor + typescript unit tests
  - **Combined run: 280/280 ✓** (registry-primary + legacy-DAG fixes coexist cleanly)
- ✅ `gitnexus` and `gitnexus-shared` typecheck clean
- ✅ Re-validated end-to-end on Sourcerer-fe with the umbrella build

**Updated headline numbers (Sourcerer-fe `src/`):**

| Metric | Clean main | Registry only | Umbrella |
|---|---:|---:|---:|
| Function nodes | 1,185 | 1,185 | **1,560** (+375) |
| F→F CALLS edges | 818 | 1,322 | **1,378** (+560, **+68.5%**) |

The +375 function nodes come from your `pair`-with-arrow capture promoting Zustand actions, TanStack `queryFn`, and React Context configs from anonymous-into-the-File status to first-class named functions — every one of those is a brand-new `gitnexus_impact` target that didn't exist before.

The TSX/JSX-as-call addition (registry-primary) and your `pair`-with-arrow patterns (mirrored in both query modules) work together: object-property arrows that previously dissolved into the File now have proper scope identity, and JSX usages of those arrow-typed components emit CALLS edges — the entire `<Container.Title />` and `addItem: () => <Foo />` style flows through end-to-end.

cc @magyargergo — all of your earlier review findings remain addressed (commit `851d2ab7`); the umbrella merge layered on top doesn't touch any of those tests.

Pushed `bb6aa0c8`. Once a maintainer approves the workflow run, CI should be fully green.

**Comment by magyargergo** [comment]
@ReidenXerx please look at these findings and ensure that the CI is healthy 🙏

**Comment by magyargergo** [comment]
@ReidenXerx thank you for your impressive work! We appreciate you taking on this challenge! 💪🏻

**Comment by ReidenXerx** [comment]
> @ReidenXerx please look at these findings and ensure that the CI is healthy 🙏

it would be really much easier for me if you could let me rerun ci pipelines by myself

**Comment by ReidenXerx** [comment]
> @ReidenXerx thank you for your impressive work! We appreciate you taking on this challenge! 💪🏻

thanks! i think your product is gem in bunch of people who tries sell useless "ai neighbourhood" services
and i really want to make it better

**Comment by magyargergo** [comment]
Come and join us on Discord and we can talk about the details ;)

File: gitnexus/src/core/ingestion/languages/typescript/query.ts [hunk 1]
```diff
@@ -136,25 +136,58 @@ const TYPESCRIPT_SCOPE_QUERY = `
...
+  key: (property_identifier) @declaration.name
+  value: (function_expression)) @declaration.function
+
+(pair
+  key: (string (string_fragment) @declaration.name)
+  value: (arrow_function)) @declaration.function
+
+(pair
+  key: (string (string_fragment) @declaration.name)
+  value: (function_expression)) @declaration.function
```
Comment (abhigyanpatwari) [inline gitnexus/src/core/ingestion/languages/typescript/query.ts]: Same anchor placement as the `lexical_declaration` fix above (lines 154-169) needs to apply here. The `@declaration.function` capture currently sits on the outer `pair` node, so `pass2AttachDeclarations` lands the def in the parent scope's `ownedDefs`. For multi-action objects like `{ addItem: ..., removeItem: ... }`, all defs end up in the same parent scope, and `resolveCallerGraphId`'s `ownedDefs.find()` attributes every call to the first sibling. Single-pair fixtures (like `bump`) mask this because there is no ambiguity, but a 2+ action Zustand store would attribute calls inside `removeItem` to `addItem`.

Could you move `@declaration.function` to the inner `arrow_function` / `function_expression` (mirroring lines 154-169) and add a multi-pair fixture that asserts each action's calls attribute to its own name? Same shape as the existing `bump` fixture but with a second action calling something different.

Comment (ReidenXerx) [reply gitnexus/src/core/ingestion/languages/typescript/query.ts]: Fixed in `66ad5c49`. Moved `@declaration.function` from the outer `pair` to the inner `arrow_function` / `function_expression` in all 4 pair patterns, mirroring the `lexical_declaration` block above. The `rangesEqual(anchor.range, innermost.range)` auto-hoist in `pass2AttachDeclarations` now does the right thing — def in the arrow's own scope, binding hoisted to the parent.

Multi-pair regression coverage:

- New fixture `multi-action-store.ts` with three pair-arrows (`addItem` / `removeItem` / `fetchData`) and three top-level call targets (`doA` / `doB` / `doC`) — exactly the Zustand shape you described.
- Four new assertions in `typescript-hof-callbacks.test.ts`: positive (`addItem → doA`, `removeItem → doB`, `fetchData → doC`), negative (no `addItem → doB`, no `addItem → doC`, no other cross-leaks), the exact-set invariant (full pair set is `{addItem→doA, removeItem→doB, fetchData→doC}`), and the regression fingerprint (`addItem → doB` MUST be `[]`).

Also updated the `useFeature → fetchData` expectation to `queryFn → fetchData` per your "or add `queryFn` as an intermediate" suggestion. The new attribution is structurally correct: `fetchData()` is called from inside the named pair-arrow `queryFn: () => fetchData()`. The pre-fix expectation only worked because the pair-pattern bug rerouted the walk past the syntactic owner — exactly the divergence from the legacy DAG you flagged. The `useFeature → useQuery` edge stays asserted (that call IS in `useFeature`'s body).

Local validation on this commit:

- `REGISTRY_PRIMARY_TYPESCRIPT=1 vitest run` — `typescript-hof-callbacks` (12, +4 new), `typescript-jsx-as-call` (7), `typescript` (236), `typescript-finalize`, `typescript-cross-file-imports`, `call-attribution-issue-1166` (18), all scope-resolution unit suites: 886/886 pass.
- Same suite without the env flag (legacy DAG path): 886/886 pass — the `tsExtractFunctionName` pair-parent handling from #1179 was already correct for multi-pair attribution; this just brings the registry-primary path to parity.
- `npx prettier --check .` clean on tracked files; `npx tsc --noEmit` clean; `npx eslint` clean on the touched files.

**Comment by ReidenXerx** [comment]
Hey @abhigyanpatwari — thanks for the thorough review. Pushed `66ad5c49` addressing the medium finding plus a quick note on the two lows.

### [medium] Pair-with-arrow anchor placement → fixed in `66ad5c49`

You were exactly right — the four `pair` patterns anchored `@declaration.function` on the outer `pair` node instead of the inner `arrow_function` / `function_expression`, and the parity gate didn't catch it because it compares which `Function` nodes exist, not edge attribution. Single-pair fixtures (`bump`, `queryFn`) masked the defect because `find()` is deterministic over a single-element set.

Inline thread: https://github.com/abhigyanpatwari/GitNexus/pull/1175#discussion_r3169039256

Summary of changes:

| File | Change |
|---|---|
| `gitnexus/src/core/ingestion/languages/typescript/query.ts` | Moved `@declaration.function` from outer `pair` to inner `arrow_function` / `function_expression` in all 4 pair patterns. Added a long anchor-discipline comment explaining *why* (mirroring the `lexical_declaration` block above). |
| `gitnexus/test/fixtures/lang-resolution/typescript-hof-callbacks/src/multi-action-store.ts` | New 3-action Zustand-shape fixture (`addItem → doA`, `removeItem → doB`, `fetchData → doC`) — the exact regression case the bug report flagged. |
| `gitnexus/test/integration/resolvers/typescript-hof-callbacks.test.ts` | +4 multi-pair attribution tests (positive, negative, exact-set, regression fingerprint). Updated `useFeature → fetchData` expectation to the structurally-correct `queryFn → fetchData`. |

Validation on `66ad5c49`:

- `REGISTRY_PRIMARY_TYPESCRIPT=1 vitest run` — typescript-hof-callbacks (12, **+4 new**), typescript-jsx-as-call (7), typescript (236), typescript-finalize, typescript-cross-file-imports, call-attribution-issue-1166 (18), all scope-resolution unit suites: **886/886 pass**.
- Same suite **without** the env flag (legacy DAG path): **886/886 pass** — your `tsExtractFunctionName` pair-parent handling already had multi-pair attribution correct on the legacy side; this just brings registry-primary to parity.
- `npx prettier --check .`, `npx tsc --noEmit`, and `npx eslint` clean on the touched files.

### [low] CI in-progress → should be green now

Both this commit and the previous `ca3d5202` (which fixed the prettier warning on `typescript.ts:107` from the #1179 merge) need maintainer "Approve and run". When it runs, the `quality / format` job that failed on `ef96603f` should now pass — verified locally with the exact `npx prettier --check .` command CI uses. Whenever you have a moment to approve, that'd be appreciated.

(Re your "let me rerun" comment from earlier — totally agreed, having to poke you for every CI run is a pain on both sides. The first-time-contributor gate seems to re-prompt on every push. Once one of these gets merged the gate should drop.)

### [low] `package.json` scope creep → I'll separate

The `gitnexus:refresh` and `gitnexus:full` scripts in `ef96603f` are unrelated to the TypeScript fix —  i decided to include it because i use it on all my projects

---

Net result: the four pair-arrow patterns now anchor exactly like the `lexical_declaration` patterns above them, multi-action Zustand stores attribute calls per-action on the registry-primary path, and the parity gate stays green because the legacy path was already correct.
